FROM maven:3.8.6-eclipse-temurin-19 AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn package

FROM eclipse-temurin:19

WORKDIR /app

COPY --from=build /app/target/*.jar account-command.jar

EXPOSE 8081